### ISSUE TITLE
[CC-PORTAL-FEEDBACK] The Latest Updates tab is not showing all of the governance actions. Eastern Cardano Council voted, Their vote is missing.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/cc-portal#403]
**Taken at**: https://constitution.gov.tools/en/latest-updates
**Fields**:
- Noticed an issue?: The Latest Updates tab is not showing all of the governance actions. Eastern Cardano Council voted, Their vote is missing.

![SCREENSHOT](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/00900783-d5a8-48da-b51d-790a29f14927-annotated_c5c5da01-9c9b-4848-9739-03d6c0722514.png?etag=a8d27da7fdf772c3de55ad063f069c86)
*[Download original image](https://resources.usersnap.com/company/9d874115-0f65-4996-8ead-fe053ac30f45/datapoint_screenshot/00900783-d5a8-48da-b51d-790a29f14927-annotated_c5c5da01-9c9b-4848-9739-03d6c0722514.png?etag=a8d27da7fdf772c3de55ad063f069c86)*

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1368x912
**Browser size**: 1368x785
**[Open #15 in Usersnap](https://app.usersnap.com/l/feedback/eadd6f1b-6b00-42c0-a967-ac72349152e8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Kale98** [comment]
@Thomas-Upfield @bosko-m Here is the update:

The user with the name: Eastern Cardano Council insert the following hot credential on the cc-portal: `4a8227024748d7ff9d52cb0ed38b715b8c41833ddfd13c0ddca93d76`. For this exact hot credential there is no vote in the db_sync database, so there is no vote on the cc-portal either.

However, for this hot address: `4012cab50266efd8c5bf8f65c0f7667352631ec086e79bf5f82f0755` there is a vote in the db_sync database and it happened on 2024-10-09 02:21:37.000 so maybe this hot credential belongs to the Eastern Cardano Council user, too. This should be checked. 

Also, this address: `4a8227024748d7ff9d52cb0ed38b715b8c41833ddfd13c0ddca93d76` exists in the db_sync database but has not been voted on, so there is no vote associated with it. Can you check whether this user has entered the right hot credential on the cc-portal, because we cannot know to whom which hot credential belongs in your db_sync, we can only see which hot credential have votes (in to db_sync)?

**Comment by Thomas-Upfield** [comment]
@Kale98 you are right about there being a duplicate hot credential, 
[https://cexplorer.io/governance/committee](![image](https://github.com/user-attachments/assets/9bf54b7d-e6cf-4cd3-90d2-4713e21fd992))
You can see from the screenshot above that one cold credential has generated two hot credentials, it is not the one beginning with 4012, it is the one beginning with 2ea. 

I will contact the Eastern Cardano Council and ask them to update their hot credential. Hopefully that fixes things.

**Comment by Thomas-Upfield** [comment]
@Kale98 I am closing this ticket as the Eastern Cardano Council have updated their hot credential and it now works. Thank you for investigating.
